// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndJCtkADyJlARX8CxH70Wy5dWbeTKpFY',
    appId: '1:413357776573:web:88944a51f6801964c8e1d4',
    messagingSenderId: '413357776573',
    projectId: 'ejection-app',
    authDomain: 'ejection-app.firebaseapp.com',
    databaseURL: 'https://ejection-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ejection-app.appspot.com',
    measurementId: 'G-V5TS8DBS4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpKJMPI6DlZdSgs2LjhPqJE9kHj_-Us4A',
    appId: '1:413357776573:android:39aa73e0bcbe09a3c8e1d4',
    messagingSenderId: '413357776573',
    projectId: 'ejection-app',
    databaseURL: 'https://ejection-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ejection-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4ZYq4HkVAEQXC1JH5_44IY66eQnXqEQ',
    appId: '1:413357776573:ios:330d3c53b2ba2c8cc8e1d4',
    messagingSenderId: '413357776573',
    projectId: 'ejection-app',
    databaseURL: 'https://ejection-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ejection-app.appspot.com',
    iosClientId: '413357776573-844or6l83f1t341fkb34hdfmuvmqu4b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejectionCenterManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4ZYq4HkVAEQXC1JH5_44IY66eQnXqEQ',
    appId: '1:413357776573:ios:330d3c53b2ba2c8cc8e1d4',
    messagingSenderId: '413357776573',
    projectId: 'ejection-app',
    databaseURL: 'https://ejection-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ejection-app.appspot.com',
    iosClientId: '413357776573-844or6l83f1t341fkb34hdfmuvmqu4b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejectionCenterManagement',
  );
}
